services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: hc_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hc_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: haneull.dv@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: